### ISSUE TITLE
Returning book doesn't work

### ISSUE THREAD

**Issue by p1nkyy** [Leseratte10/acsm-calibre-plugin#31] opened 2022-08-14 15:53 UTC
### Bug description

Hello, I mainly borrowed books from Overdrive or BorrowBox. Returning books don't really work. I click the arrow, it said 'Book is returned' and it disappeared from the Show Loaned Books list, but when I get back to the library's 'Loan' page, the book is still there and not yet returned. Only when I click Return manually will the book disappear. I currently am waiting for 1 book that I returned from the plugin to see whether after several hours it will be returned in Overdrive.
I don't know what debug process to include but let me know what to do so I can help. Thanks!

### Operating system

Windows

### Which version of Calibre are you running?

6.0

### Which version of the DeACSM plugin are you running?

v0.0.16

**Comment by Leseratte10** [comment] 2022-08-14 17:51
Can you test if returning books through ADE works fine? Maybe the library just didn't implement book returns correctly and it would fail with ADE, too. 

If it works just fine with ADE, can you start calibre in debug mode (The drop-down menu "Preferences", then "Restart in debug mode"). Once you're in debug mode, try to return another book then close Calibre. After that the log file should open in a text editor, then just post that log here and I'll check if I can see anything that looks wrong.

**Comment by p1nkyy** [comment] 2022-08-15 03:50
Yes my ADE is indeed very unstable. It keeps freezing every second, even when I do nothing at all and I need to end it via Task Manager. Can this affect it? I can return the books fine though via ADE when it's working. de-ACSM also don't always work in the first time.
This is when de-ACSM doesn't work and the ACSM files remain ACSM files

`calibre Debug log
calibre 6.0  embedded-python: True
Windows-10-10.0.19043 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Find Duplicates (1, 9, 7) && KindleUnpack - The Plugin (0, 83, 1)
calibre 6.0  embedded-python: True
Windows-10-10.0.19043 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Find Duplicates (1, 9, 7) && KindleUnpack - The Plugin (0, 83, 1)
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 74.03111954459203 x 74.14054054054054
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
[0.92] main UI initialized...
[0.92] Hiding splash screen
Starting QuickView
[8.74] splash screen hidden
[8.74] Started up in 8.74 seconds with 4082 books
Running file type plugin DeACSM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.deacsm.__init__", line 422, in run
  File "calibre_plugins.deacsm.__init__", line 324, in download
  File "C:\Users\Diana\AppData\Roaming\calibre\plugins\DeACSM.zip\libadobe.py", line 267, in sendHTTPRequest_DL2FILE
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
Running file type plugin DeACSM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.deacsm.__init__", line 422, in run
  File "calibre_plugins.deacsm.__init__", line 324, in download
  File "C:\Users\Diana\AppData\Roaming\calibre\plugins\DeACSM.zip\libadobe.py", line 267, in sendHTTPRequest_DL2FILE
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
DeACSM v0.0.16: Trying to parse file NamedoftheDragon9780749014964.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acsepub.contentreserve.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
Notifying optional server https://ofs.contentreserve.com/ACSNotificationService.svc/Notify
Weird Fulfillment Notification response: 
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://acs.cdn.overdrive.com/ACSStore1/1486-1/DC4/958/78/{DC495878-9861-43DA-9D76-F1CD6F511866}Fmt410.epub
DeACSM v0.0.16: Trying to parse file Mariana.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acsepub.contentreserve.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
Notifying optional server https://ofs.contentreserve.com/ACSNotificationService.svc/Notify
Weird Fulfillment Notification response: 
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://acs.cdn.overdrive.com/ACSStore1/1486-1/EB3/ACD/E9/{EB3ACDE9-5C99-4E95-846D-5B60589B78BF}Fmt410.epub
Added NamedoftheDragon9780749014964 to db in: 2.1
Added Mariana to db in: 1.3
Added 2 books in 8.2 seconds
`

This is when returning book:

`calibre Debug log
calibre 6.0  embedded-python: True
Windows-10-10.0.19043 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Find Duplicates (1, 9, 7) && KindleUnpack - The Plugin (0, 83, 1)
calibre 6.0  embedded-python: True
Windows-10-10.0.19043 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Find Duplicates (1, 9, 7) && KindleUnpack - The Plugin (0, 83, 1)
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 74.03111954459203 x 74.14054054054054
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[0.94] main UI initialized...
[0.94] Hiding splash screen
Starting QuickView
[2.41] splash screen hidden
[2.41] Started up in 2.41 seconds with 4084 books
Returning book The Shadowy Horses (6d 23h remaining) (ID e15eacc4-42be-46cb-a7a7-df9354e86451-0002eb66)
Would notify server https://acsepub.contentreserve.com/fulfillment/LoanReturn:
Loan return successful
Notifying optional server https://ofs.contentreserve.com/ACSNotificationService.svc/Notify
Weird Fulfillment Notification response: 
Book successfully returned.
Deleting book entry The Shadowy Horses (6d 23h remaining) (ID e15eacc4-42be-46cb-a7a7-df9354e86451-0002eb66)
`

**Comment by Leseratte10** [comment] 2022-08-15 04:05
Okay, the first error (ACSM not turning into an EPUB) is because the overdrive server returned a 404 HTTP error while trying to download the book. This is usually a server error / temporary outage at overdrive. I can try to have the plugin retry upon encountering the first 404 error but I don't think that has a high chance of working. You'd probably get similar errors in ADE from time to time. Does this error go away when you import the same ACSM file later, or re-download the ACSM file?

As for returning books, I currently don't know why that didn't work. I'll add some more debug logging to the plugin for book returns and will let you know when that's done so you can send another debug log.

**Comment by p1nkyy** [comment] 2022-08-15 04:26
No, I rarely encountered ADE unable to process ACSM. This time, they return with "Error getting license. License server communication problem. E_ADEPT_NO_FULFILLMENT_RESULT" with 2 books. But maybe you're right, it's OD that is currently down. I tried to use ACSM from Google Play and it works immediately.
Just need the Returning feature to work because in BorrowBox, once you process it through ADE, you can only return the book via ADE and not the site (in OD we can still go back to the library and return manually) and my ADE is too unstable and almost unusable at the moment to be able to do that. Thanks for responding to me so far!

**Comment by Leseratte10** [comment] 2022-09-03 07:38
Interesting. I've just had this exact issue (book return apparently successful but the book is not returned at the library) happen with the library I'm regularly using. I wonder if Adobe has changed something in how library returns work, because I definitely remember successfully returning books in the past. 
And I can't see anything useful in the logs. 

I guess I need to spin up ADE2 again on a Windows machine and compare dumps ...

**Comment by p1nkyy** [comment] 2022-09-03 14:41
Yeah if you could look into it, I'd be immensely grateful. My ADE is literally unusable, just moving it around will freeze it and no amount of install & uninstalling could fix it. I am so thankful for your plugin because I don't have to deal with ADE but I really need the return book feature because BorrowBox (unlike Overdrive) only gives you option to return from the ADE if the book is processed through ADE.

**Comment by Leseratte10** [comment] 2022-09-03 17:00
Okay, I just messed around with ADE a bit and found some parts of the book return process that my plugin doesn't implement correctly. ACS 5 (which was introduced with ADE 3 and which most book stores used in the past) didn't care, but ACS 6 (introduced with ADE 4) apparently does. 

I'll try to get this implemented into the plugin ASAP and will let you know when there's a new test version.

**Comment by Leseratte10** [comment] 2022-09-03 17:37
Interesting. I fixed that bug but it's still not working ...

**Comment by Leseratte10** [comment] 2022-09-03 18:49
Hm. Did not manage to get it to work reliably, but I don't want to mess with the library always loading and returning books. I'll leave this issue open, maybe I'll get another idea later.

**Comment by Leseratte10** [comment] 2022-09-04 08:10
@p1nkyy 
Can you test this version and see if that works? Seems to work for my library, at least, but I didn't want to do that many tests because loaning then immediately returning books is probably suspicious ...

You'll have to loan a new book with that version to test this, I doubt the bugfix works when returning books downloaded with the old version.

Let me know if this fixes the issue, please. 

[calibre-plugin_test_build_bookreturn.zip](https://github.com/Leseratte10/acsm-calibre-plugin/files/9484273/calibre-plugin_test_build_bookreturn.zip)

**Comment by Leseratte10** [comment] 2022-09-04 09:18
Would you mind testing if c6b9e5c59bf6fe965b959a6ee208d546b9118146 fixes the issue? I believe I found and fixed the bug. 

You can download that version [from the Github Actions page](https://github.com/Leseratte10/acsm-calibre-plugin/suites/8125468941/artifacts/351884390). 
The issue got auto-closed because I mentioned the issue number in the commit message, if this does not fix the issue just open it again.

**Comment by p1nkyy** [comment] 2022-09-04 15:02
> 

Sure, I will test it and get back to you. Thanks a lot!

**Comment by p1nkyy** [comment] 2022-09-04 15:28
Yes it works!! You're a genius! Thanks a lot!!

**Comment by Leseratte10** [comment] 2022-09-04 15:29
Great, I will include that fix in the next version then. Thanks for testing.

**Comment by p1nkyy** [comment] 2022-09-04 16:01
> Great, I will include that fix in the next version then. Thanks for testing.

Will I get auto update notif if I'm running this alternative version?

**Comment by Leseratte10** [comment] 2022-09-04 16:21
Good question. I assume yes, but I've never tested it before.

**Comment by p1nkyy** [comment] 2022-09-06 02:05
Hello found 2 bugs here, if you could re-open this issue, thanks. (I couldn't maybe because you're the author and you closed it)
1. Processing >1 ACSM file from 1 library will show only 1 titles in the 'Loaned Book List'. I need to add the others one by one later on OR add them 1 by 1 since the beginning and not just a bunch at once.

2. There is 1 instance of returning book didn't work, the title is still in BorrowBox, BUT when I re-downloaded and processed the ACSM, they don't work or don't get converted to .ePUB.
Usually in normal ADE the message given back would be E_BAD_LOAN_ID or E_LICENSE_ALREADY_RETURNED (not the exact wording)
So: returning > book still show up > tried the same ACSM > not converted into epub > downloaded fresh ACSM from the Borrowbox > still doesn't work

[log 3.txt](https://github.com/Leseratte10/acsm-calibre-plugin/files/9492753/log.3.txt)

**Comment by Leseratte10** [comment] 2022-09-06 04:42
1. That's interesting. I guess I never tested adding multiple books from a library at once. I'll take a look at that. 
2. If, during redownload, you get the error `E_LIC_ALREADY_RETURNED` (as it's the case in your log file), that means according to Adobe, the book return was definitely successful and Adobe thinks the book's been properly returned. Why that information didn't make it to BorrowBox - no idea. How many books did you test? Was this like 1 out of 3 where it didn't work (which could be a bug in the plugin) or more like 1 out of 20 (which might as well have been a small glitch or bug at BorrowBox)?

**Comment by p1nkyy** [comment] 2022-09-06 04:55
E_LIC_ALREADY_RETURNED only happened this one time with de-ACSM. Previously with my very unstable ADE, if I am in the middle or returning and my ADE froze, this will cause this error to happen, that ADE said it has been returned but Borrowbox still think it hasn't. I have several books that I can't return at the moment in BorrowBox due to this (ADE froze all the time).

Because it can't be predicted when this error would happen, don't think I'd be able to capture it as I'm not using the debug mode all the time but could it be internet connection problem?

**Comment by Leseratte10** [comment] 2022-09-06 05:05
Could be, yes. 
While the process of returning a book to Adobe (which is what marks the loan as returned so you'd get `E_LIC_ALREADY_RETURNED` on another download attempt) is standardized and identical for each library (which means it's easier for me to debug), the process of returning a book to the actual library is different for each library, so it's difficult or even impossible for me to add proper error checking and/or having the plugin verify if the book return was *really* successful. 

So I guess we'll mark that as a one-off error, unless you notice it happen more often. 

As for the loan record issue, I've just had that happen as well while trying to fulfill three ACSM files at once. How many did you try to add at once?

Looking at the log from my attempt, this most likely happens because the process is like "get the existing loan list, add the new book to it, then write back the new list that has one more book". But since Calibre is processing all three ACSM files in parallel and not one after the other, what probably happens is that the loan records for two books were created at the exact same time, both "instances" of the plugin grabbed the then-current loan list, each added "their" book to the copy of the list, and then wrote their list back to the config file, when one instance overwrote the changes of the other. 

So, I'll have to make that process atomic so multiple instances don't overwrite data. I'll look into that.

**Comment by p1nkyy** [comment] 2022-09-06 05:32
1. Yes, I also think it should be a one-off incident.

2. Yes, I now remembered I processed 3 at once at first and the other instance defo more than 3 as well. 
However, I have since processed 30 new books using the 0.0.17 and all titles are accounted for in the Loaned List. Not all 30 at once, but perhaps 5-10 at once.

**Comment by p1nkyy** [comment] 2022-09-14 13:05
![image](https://user-images.githubusercontent.com/7593831/190161439-e9a66a13-1b83-48bd-ab8a-6a8fe649e680.png)

Hello, is this the intended behavior? Old books don't get removed from the Show Loaned List after their loan period ends. Thanks!

**Comment by Leseratte10** [comment] 2022-09-14 13:56
That's definitely not intended, books are supposed to disappear from that list once the time is up. I'll take another look.

**Comment by Leseratte10** [comment] 2022-10-08 16:37
The bug with old entries not always getting removed from that list is now fixed with the latest commit. 

Now that loaned books and loan management should work as intended, I'm going to close this issue and open a new one for the still-existing issue that happens when importing multiple ACSM files at once, as that doesn't really have anything to do with returning books.

**Closed by Leseratte10** 2022-10-08 16:37 UTC
Labels: bug

**Comment by p1nkyy** [comment] 2022-10-09 07:30
Sorry for the silly question but do I re-download v0.16 to be able to get this issue solved?

**Comment by Leseratte10** [comment] 2022-10-09 07:51
Nope, the 0.0.16 download hasn't been changed. The bugfix will be in the next version that's not released yet. If you want, you can download the test version from https://github.com/Leseratte10/acsm-calibre-plugin/suites/8680259517/artifacts/391182561

**Comment by p1nkyy** [comment] 2022-10-09 07:53
I want to ask about something else, can you share me your e-mail? I tried to submit a bug but the Submit button can't be clicked, even though I've filled everything.

**Comment by Leseratte10** [comment] 2022-10-09 08:23
The Submit button automatically becomes available once all the necessary fields are filled out (Title, Description, Operating System, Calibre version, plugin version). If that doesn't work for some reason you can also click on the "[Open a blank issue](https://github.com/Leseratte10/acsm-calibre-plugin/issues/new)" link and open an issue without the form.
