### ISSUE TITLE
Apostrophe in title got converted to weird unicode

### ISSUE THREAD

**Issue by p1nkyy** [Leseratte10/acsm-calibre-plugin#38] opened 2022-10-09 12:15 UTC
Hello, sometimes, a book title that has apostrophe in the title got converted into weird unicode (â€™) so for example: _The Bookseller's Apprentice_ becomes _The Booksellerâ€™s Apprentice_. The folder name becomes _The BookselleraEUTMs Apprentice - Amelia Mellor_.
Is this due to Calibre, ADE, the plugin, Windows?
Haven't figured out the situation that caused this. Should I send a log when re-processing these titles?

Attached is some screenshot:
![image](https://user-images.githubusercontent.com/7593831/194756255-9f418372-45bf-4bef-90f5-ef5fb182274d.png) ![image](https://user-images.githubusercontent.com/7593831/194756281-64e759b0-56e3-4b20-8fec-d5153c1f7a77.png) ![image](https://user-images.githubusercontent.com/7593831/194756299-efc44094-6c01-4b7d-a9ad-3abc84815660.png)

**Comment by Leseratte10** [comment] 2022-10-09 14:06
Does this happen with all books that have an apostrophe in their name, or only with some? 

My first guess would be that that's an issue with the book shop / whoever generates the ACSM file or the ebook. Can you post a debug log of an attempt that creates such a file?

**Comment by p1nkyy** [comment] 2022-10-09 14:12
Only some and very random and only started recently (September).
OK, will try to send one if I encounter this again.

**Comment by p1nkyy** [comment] 2022-10-14 13:01
[log 4.txt](https://github.com/Leseratte10/acsm-calibre-plugin/files/9786479/log.4.txt)

Hi, finally it has happened again and here's the log for you. Hope it's useful!

**Comment by Leseratte10** [comment] 2022-10-14 14:15
Can you re-do that log with the verbose log setting enabled if you still have the ACSM file?
Do you happen to have an install of ADE with the same AdobeID to check if the same error occurs when downloading with ADE?

**Comment by p1nkyy** [comment] 2022-10-14 14:21
Sorry for being silly but how do I enable the verbose log?
No I have long uninstalled ADE because it's practically unusable. Should I send you this acsm so you can process it? (Clean re-borrowed ACSM that I haven't processed so it won't say already fulfilled)

**Comment by JJTech0130** [comment] 2022-10-14 15:07
> Sorry for being silly but how do I enable the verbose log?
Open Calibre, then click "Preferences" -> "Restart in debug mode". Then Calibre will restart, then perform the action that causes the error (probably adding the ACSM file), then close Calibre. A text file should then be opened with some more verbose logs.

**Comment by p1nkyy** [comment] 2022-10-14 15:14
> 

That was what I did with the log above. If just opening & closing it again then here it is.

[log 5.txt](https://github.com/Leseratte10/acsm-calibre-plugin/files/9787677/log.5.txt)

**Comment by p1nkyy** [comment] 2022-10-15 02:33
![image](https://user-images.githubusercontent.com/7593831/195965011-4d3e89cc-b83a-4388-a825-4146c11d994a.png)
Is it here? If yes, don't see any option to enable verbose debug logging

**Comment by mwsundberg** [comment] 2022-10-15 02:53
I have the same issue and can send you an example file, the key/config used for the DeACSM plugin, and the debug log. I'd prefer to share those elsewhere and not publicly upload the files, may I email you?
It's also not reading the metadata, yet I don't know if it's an issue with my library's files or the plugin/Calibre.
I'm using deACSM v0.0.16 downloaded from the Releases tab, DeDRM 10.0.3 from noDRM's fork, and Calibre 6.7 on Windows 10. For the ADE account I'm using an auto-generated anonymous one.

**Comment by p1nkyy** [comment] 2022-10-15 03:27
Yeah, I would like to corresponds via e-mail instead for some of these questions but he was hesitant to share his e-mail, hopefully he'll let us know soon. With yours @mwsundberg is it all titles that has apostrophe converted into unicode or just randomly like mine?

**Comment by Leseratte10** [comment] 2022-10-15 07:50
I don't really like publicly sharing my main email (hello bot spam!) so here's a dedicated one for this issue that I can delete again once the issue is solved: 

s4-tmp-st2y4wgcz97k-github-acsm-38@leseratte10.de 

You can send verbose log files (or even whole authorizations and/or ACSM files if you're comfortable with that) to this address and I'll take a look.

**Comment by Leseratte10** [comment] 2022-10-15 09:34
Thanks for your email @mwsundberg , to me this issue looks like it's a bug either in Calibre (more likely) or in the book itself (less likely), not in my plugin. I took the book EPUB file that comes straight from the yourcloudlibrary.com server before it was processed by my plugin, removed all the actual content and data (so it's legal to share now) and just kept title and author as-is. 

When I import that book into Calibre I get the same weird book title as you - I attached it here for reference. 

[ef3a1633-95ce-4752-9c45-6c6905ac178c.epub.zip](https://github.com/Leseratte10/acsm-calibre-plugin/files/9791706/ef3a1633-95ce-4752-9c45-6c6905ac178c.epub.zip)

Probably because the title uses one of these weird, non-ASCII, Unicode apostrophes - **`’`** instead of the normal one **`'`**. Though, I'm surprised Calibre doesn't like these. I've ran the resulting EPUB through a validation tool and it didn't complain about the book name. Other EPUB reading tools also display the book title correctly. 

I'll open a Calibre bug report and link it here for reference; that bug is not something that I can fix in my plugin. You can verify that by checking that EPUB I linked with other readers (correct title) and importing it into Calibre (wrong title).

**Comment by mwsundberg** [comment] 2022-10-15 10:23
Cool, thanks for the quick follow-up and debugging a problem that ultimately had nothing to do with your plugin.

**Comment by p1nkyy** [comment] 2022-10-15 11:29
Wow after waiting for quite some time and it's resolved finally haha. OK I don't need to send in my ACSM then. Thanks for the answers @Leseratte10 and thanks for your input @mwsundberg

**Comment by Leseratte10** [comment] 2022-10-15 11:44
@p1nkyy I checked your email / ACSM as well and it seems to be the exact same issue with the unicode apostrophe, so once that Calibre bug is fixed the issue should be gone.

**Comment by Leseratte10** [comment] 2022-10-15 13:07
The bug in Calibre has now been fixed with kovidgoyal/calibre@ad34b0ea3b2d0ba514e93d17b060a3d9af1247eb and I confirmed that both EPUB files now display the apostrophe correctly with that version. The bugfix will be included in the next Calibre update which I assume will happen in two weeks. I'm going to close this issue for now, if the bug still occurs after the next Calibre update you can comment again or re-open this and I'll take another look.

**Closed by Leseratte10** 2022-10-15 13:07 UTC
Labels: bug, invalid
