### ISSUE TITLE
Passwords using the extended ascii charset fail the login

### ISSUE THREAD

**Issue by Nydragon** [Leseratte10/acsm-calibre-plugin#93] opened 2024-06-08 15:47 UTC
### Bug description

Accounts with more complex passwords such as:
```Msin¶^rmTáÅv)|h¹2ËýYB\8L¯ÓWOÔê```
 fail to login, while
```]wOm~c[(!f6m3Ybp[M~2.&cwEE```
works fine.

The difference is the addition of the exended ascii charset (128-255) in the first password.

### Operating system

Linux

### Which version of Calibre are you running?

7.11

### Which version of the ACSM Input plugin are you running?

27bd9531c44f9896e4ade81c768c12e393e51e9a

**Comment by Leseratte10** [comment] 2024-08-07 04:40
This is probably due to the fact how the bytes for the login key are assembled (in "encryptLoginCredentials" in libadobeAccount.py: 

```py
    # Build buffer <devkey_bytes> <len username> <username> <len password> <password>

    ar = bytearray(devkey_bytes)
    ar.extend(bytearray(struct.pack("B", len(username))))
    ar.extend(bytearray(username.encode("latin-1")))
    ar.extend(bytearray(struct.pack("B", len(password))))
    ar.extend(bytearray(password.encode("latin-1")))
```

Looks like this was never used with characters outside the normal printable standard ASCII. Did you test / can you confirm whether normal ADE works fine with passwords like these?

I'm going to give it a try when I have time to set such a password for my account and see if I can modify that code to make it work.

**Comment by Leseratte10** [comment] 2024-08-07 07:31
Thanks for reporting this, the issue is now fixed with the new commit.

**Closed** 2024-08-07 07:31 UTC

**Comment by Nydragon** [comment] 2024-08-07 15:47
Thank you for fixing the issue!
