### ISSUE TITLE
When Calibre thinks book is a duplicate, file is not processed by DeACSM

### ISSUE THREAD

**Issue by Gwouigwoui** [Leseratte10/acsm-calibre-plugin#46] opened 2023-01-25 18:54 UTC
When I import automatically an ACSM file and a similar ebook exists in the library, Calibre asks if I want to import the book anyway. This somehow prevents the new ACSM from being processed by DeACSM.

**Comment by Leseratte10** [comment] 2023-01-25 18:56
I've just tested that and it's working fine for me. 

Do other (non-duplicate) books work for you? 

Can you please post a debug log? Right-click the "Preferences" button, choose "Restart in debug mode", then import an ACSM and close Calibre, then post the debug log file that shows up.

**Comment by Gwouigwoui** [comment] 2023-01-25 19:02
Here you go!
[debug.txt](https://github.com/Leseratte10/acsm-calibre-plugin/files/10502660/debug.txt)

**Comment by Gwouigwoui** [comment] 2023-01-25 19:09
I'm using the watch folder. When I drop a file in there, apparently Calibre checks if there are possible duplicates and ask if I want to proceed if it finds there might be one. When it's an EPUB, no problem, the book appears in my library as expected, but when it's an ACSM the file is moved into its own folder and appears in the library as well, but without being processed by DeACSM, just an ACSM file.
Maybe Calibre moves it first so your plugin can't find it anymore in the watch folder? This would explain the error (FileNotFoundError).

**Comment by Leseratte10** [comment] 2023-01-25 19:18
Okay, when I A) use the auto-add folder, and B) I have the "Check for duplicates" option in the auto-add settings enabled, I can reproduce the error, though I'm not sure yet what causes it because the logging isn't working properly for some reason with auto-added books. 

As a workaround you could disable the duplicate detection for auto-added books if you always want it to add duplicates. I'll take a look to see if I can fix this bug in my plugin or if it needs to be fixed in Calibre.

**Comment by Gwouigwoui** [comment] 2023-01-25 19:41
Ok, thanks!

    Le mercredi 25 janvier 2023 à 14:18:29 UTC−5, Florian Bach ***@***.***> a écrit :  
 
 


Okay, when I A) use the auto-add folder, and B) I have the "Check for duplicates" option in the auto-add settings enabled, I can reproduce the error, though I'm not sure yet what causes it because the logging isn't working properly for some reason with auto-added books.

As a workaround you could disable the duplicate detection for auto-added books if you always want it to add duplicates. I'll take a look to see if I can fix this bug in my plugin or if it needs to be fixed in Calibre.

**Comment by Leseratte10** [comment] 2023-01-25 19:55
I took a closer look and this seems to be a bug in Calibre, not in my plugin. Looks like nobody has ever used my plugin with the auto-add folder and enabled duplicate detection. 

I've reported the bug to the Calibre developers, hoping that they can fix that issue: https://bugs.launchpad.net/calibre/+bug/2003906

**Comment by Leseratte10** [comment] 2023-01-31 10:26
This bug should now be fixed in Calibre, if you [set up a development environment](https://manual.calibre-ebook.com/develop.html#windows-development-environment) you can already test it, otherwise you can wait until the next Calibre update.

**Comment by Gwouigwoui** [comment] 2023-01-31 15:02
Excellent, thanks for the follow-up!

    Le mardi 31 janvier 2023 à 05:26:15 UTC−5, Florian Bach ***@***.***> a écrit :  
 
 


This bug should now be fixed in Calibre, if you set up a development environment you can already test it, otherwise you can wait until the next Calibre update.

**Comment by Leseratte10** [comment] 2023-02-10 20:03
Can you confirm that this is now fixed in Calibre 6.12? Then I can close this issue.

**Comment by Gwouigwoui** [comment] 2023-02-10 20:35
Yup, it's all good, thanks again!
________________________________
De : Florian Bach ***@***.***>
Envoyé : Friday, February 10, 2023 3:03:23 PM
À : Leseratte10/acsm-calibre-plugin ***@***.***>
Cc : Gwouigwoui ***@***.***>; Author ***@***.***>
Objet : Re: [Leseratte10/acsm-calibre-plugin] When Calibre thinks book is a duplicate, file is not processed by DeACSM (Issue #46)


Can you confirm that this is now fixed in Calibre 6.12? Then I can close this issue.

**Closed** 2023-02-11 18:45 UTC
