### ISSUE TITLE
Unable to decrypt pdf

### ISSUE THREAD

**Issue by thekalinga** [Leseratte10/acsm-calibre-plugin#7] opened 2021-11-05 21:32 UTC
I tried download a pdf from acsm file. Unfortunately, the pdf is not downloaded by Calibre.

I have attached a sample acsm thats new & unfufilled (I have not downloaded pdf using the acsm). I tried with a different file (but from same website) & its not working

Environment
```
Ubuntu 16.04

Calibre 5.31.1
```

[police-abuse-and-killings-of-street-children-in-india.acsm.zip](https://github.com/Leseratte10/acsm-calibre-plugin/files/7489032/police-abuse-and-killings-of-street-children-in-india.acsm.zip)

**Comment by Leseratte10** [comment] 2021-11-05 21:36
I just downloaded that ACSM file, imported it into Calibre and it does turn into a valid, readable PDF file, so I cannot confirm this issue. 

Can you run Calibre in debug mode (Preferences -> Restart in debug mode), then import the ACSM, then close Calibre, and then send me the resulting log file / attach it to this issue report so I can take a look at what exactly is failing for you?

**Comment by thekalinga** [comment] 2021-11-05 21:38
Are you able to view the pdf?

**Comment by Leseratte10** [comment] 2021-11-05 21:39
Yes, I am. 
Does the tool fail to *download* the PDF, or does it download the PDF but it is unreadable due to DRM? This plugin does not remove DRM on its own, you'll need the DeDRM plugin to do that. And that plugin needs custom patches to work properly with PDFs.

**Comment by thekalinga** [comment] 2021-11-05 21:42
Oh OK..

Its downloading the pdf. Its locked due to DRM. I have the DeDRM plugin, but I dont have custom patches for PDFs :(

Is there a place where I can get patched DeDRM plugin?

**Comment by thekalinga** [comment] 2021-11-05 21:43
custom patch* for pdf

**Comment by Leseratte10** [comment] 2021-11-05 21:51
I'm not sure if there's an already packaged version of the patched DeDRM plugin, but the necessary changes are described here: https://github.com/apprenticeharper/DeDRM_tools/pull/1689 
As this is not a bug with my plugin, I'm going to close this issue then.

**Closed by Leseratte10** 2021-11-05 21:51 UTC

**Comment by thekalinga** [comment] 2021-11-05 21:59
Thanks for that.

I made the following changes

1. Uninstalled both DeDRM & ACSM plugins from Calibre
2. Extracted DeDRM plugin source
3. Made changes in pull request #1689 to `ineptpdf.py`
4. Also made additional change you suggested to `ineptpdf.py` (attached modified `ineptpdf.py`)
5. Zipped DeDRM plugin
6. Installed modified DeDRM plugin & ACSM plugin
7. Ensured ACSM plugin was authorised with Adobe
8. Opened ACSM. I still have the same issue :(

Pdf is downloaded, but its not decrypted. Evience is saying the document is locked :(

[ineptpdf.py.zip](https://github.com/Leseratte10/acsm-calibre-plugin/files/7489115/ineptpdf.py.zip)

![image](https://user-images.githubusercontent.com/452518/140583161-b027a9c3-fb4b-4fb9-b5f8-40012f65d8bc.png)

**Comment by Leseratte10** [comment] 2021-11-05 22:01
Can you run Calibre in debug mode (Preferences -> restart in debug mode), then import the ACSM, then close Calibre and send me the log file?

**Comment by thekalinga** [comment] 2021-11-05 22:12
I dint manually export the key from ACSM & import it in DeDRM. Now I did it. That solved the issue. Thanks a lot.
